spring:
  application:
    name: pharmquest # 애플리케이션 이름 설정
  datasource:
    url: jdbc:mysql://localhost:3306/pharmquest?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ""
    password: ""
  jpa:
    hibernate:
      ddl-auto: update # 테이블을 자동 생성/업데이트
    database-platform: org.hibernate.dialect.MySQLDialect # MySQL Dialect 설정
    show-sql: true # 실행되는 SQL 출력
    properties:
      hibernate:
        format_sql: true # 출력되는 SQL 포맷팅
