name: CI/CD Pipeline

on:
  push:
    branches: [ main ]  # main 브랜치에 push가 발생하면 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository Checkout
      - uses: actions/checkout@v3  # GitHub 저장소 코드 가져오기

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Set Environment Variables
      - name: Set Environment Variables
        run: |
          echo "SPRING_PROFILES_ACTIVE=prod" >> $GITHUB_ENV
          echo "GOOGLE_APPLICATION_CREDENTIALS=/home/ubuntu/google-key.json" >> $GITHUB_ENV
        shell: bash

      # 4. Generate application.yml
      - name: Generate application.yml
        run: |
          cd ./src/main/resources
          echo "${{ secrets.APPLICATION_DEV_YML }}" > ./application.yml
        shell: bash

      # 5. Grant execute permission for Gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 6. Build with Gradle
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      # 7. Upload build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: umc7thServer
          path: build/libs/*.jar

  deploy:
    needs: build  # Build 작업 완료 후 실행
    runs-on: ubuntu-latest

    steps:
      # 1. Download build artifact
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: umc7thServer
          path: build/libs/

      # 2. Generate Google Cloud JSON Key
      - name: Generate Google Cloud Json Key
        run: |
          mkdir -p /home/ubuntu  # 디렉토리 생성
          echo "$GOOGLE_APPLICATION_CREDENTIALS" > /home/ubuntu/google-key.json
          chmod 600 /home/ubuntu/google-key.json

      # 3. Deploy to EC2
      - name: Deploy to EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "$EC2_SSH_KEY" > private_key.pem
          chmod 600 private_key.pem
          jar_file=$(find build/libs -name '*.jar' ! -name '*plain.jar' | head -n 1)
          scp -i private_key.pem -o StrictHostKeyChecking=no "$jar_file" $EC2_USERNAME@$EC2_HOST:/home/$EC2_USERNAME/umc7thServer.jar
          scp -i private_key.pem -o StrictHostKeyChecking=no /home/ubuntu/google-key.json $EC2_USERNAME@$EC2_HOST:/home/$EC2_USERNAME/google-key.json
          ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_HOST "
            pgrep java | xargs -r kill -15  # 기존 Java 프로세스 종료
            sleep 10
            export GOOGLE_APPLICATION_CREDENTIALS=/home/$EC2_USERNAME/google-key.json
            nohup java -jar /home/$EC2_USERNAME/umc7thServer.jar > app.log 2>&1 &
          "
          rm -f private_key.pem  # 민감한 정보 삭제
